import { useState, useEffect } from 'react';
import { Cpu, RefreshCw, Download } from 'lucide-react';
// @ts-ignore
import ReactMarkdown from 'react-markdown';

export default function Intelligence() {
  const [report, setReport] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(false);

  const fetchMacroReport = async () => {
    setLoading(true);
    setReport('');
    try {
      const res = await fetch('http://localhost:8000/api/ai/macro', { method: 'POST' });
      const data = await res.json();
      if (data.report) {
        setReport(data.report);
      }
    } catch (e) {
      console.error(e);
      setReport('Failed to fetch the intelligence report from the AI engine.');
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    if (!report) return;
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `QuantLens_Macro_Intelligence_${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  useEffect(() => {
    fetchMacroReport();
  }, []);

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-end">
        <div>
          <h1 className="text-2xl font-bold text-white mb-2 flex items-center gap-2">
            <Cpu className="text-secondary" />
            AI Market Intelligence
          </h1>
          <p className="text-textMuted text-sm">Macro-level market analysis generated by the Failover AI Engine.</p>
        </div>
        <div className="flex items-center gap-3">
          <button 
            onClick={handleDownload} 
            disabled={!report || loading}
            className="bg-surface hover:bg-surfaceHover border border-border text-white font-medium py-2 px-4 rounded-lg transition-colors flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <Download className="w-4 h-4" />
            Download
          </button>
          <button 
            onClick={fetchMacroReport} 
            disabled={loading}
            className="bg-surface hover:bg-surfaceHover border border-border text-white font-medium py-2 px-4 rounded-lg transition-colors flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
            {loading ? 'Generating...' : 'Refresh'}
          </button>
        </div>
      </div>

      <div className="card">
        {loading ? (
          <div className="flex flex-col items-center justify-center py-20 space-y-4">
            <div className="w-8 h-8 border-4 border-secondary border-t-transparent rounded-full animate-spin"></div>
            <p className="text-textMuted text-sm animate-pulse">Synthesizing global market data...</p>
          </div>
        ) : (
          <div className="prose prose-invert max-w-none prose-p:text-textMuted prose-headings:text-white prose-strong:text-white">
            <ReactMarkdown>{report}</ReactMarkdown>
          </div>
        )}
      </div>
    </div>
  );
}
